### ISSUE TITLE
Fatal error: Uncaught TypeError: Unsupported operand types: null & array

### ISSUE THREAD

**Issue by cy-polo** [evert/SabreAMF#10]
Hello,

I'm trying to configure a small `AMF server` in `PHP`, but I get an error that seems to come from `SabreAMF` that I don't understand, when creating the AMF server (`new SabreAMF_Server()`).
Can you please help me?

Here is what I do:

```php
<?php
try
{
    session_start(); // start session to store data between requests
    set_error_handler(function($errno, $errstr, $errfile, $errline, $errcontext) {
        if (0 === error_reporting()) {
            return false;
        }

        throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
    });

    include "vendor/autoload.php";
    include "BaseService.php";
    include "Utils.php";

    // $pdo = new PDO("mysql:host=127.0.0.1;dbname=mspps;charset=utf8", "", "");
    $pdo = new PDO("mysql:host=localhost;dbname=mspps", "root", "");

    foreach (array_merge(glob("webservices/*.php"), glob("classes/*.php")) as $filename)
        include $filename;

    $server = new SabreAMF_Server(); // ERROR HERE, TO WATCH BELLOW

    $request = $server->getRequests()[0];
    $target = $request["target"];
    $data = $request['data'];

    $classIndex = count(explode(".", $target)) - 2;
    $exploded = explode(".", $target);
    $webserviceClass = $exploded[$classIndex];
    $function = $exploded[$classIndex + 1];

    if (class_exists($webserviceClass)) 
    {
        $class = new $webserviceClass($data);
        if (method_exists($class, $function)) 
        {
            $response = $class->{$function}(...$data);
        }
    }
        
    $vars = get_defined_vars();
    if (array_key_exists('response', $vars)) 
    {
        $server->setResponse(
            $request["response"],
            SabreAMF_Const::R_RESULT,
            $response
        );
    }

    $server->sendResponse();
}
catch (Exception $e)
{
    $_SESSION["error"] = "Error at: " . str_replace("D:\\xampp\\htdocs\\webservices", "", $e->getFile()) . ":" . $e->getLine() . ": '" . $e->getMessage() . "'\n\nStack trace:\n" . $e->getTraceAsString();
    http_response_code(500);
    die();
}
```

Here is my error:
<p><br /><strong>Fatal error</strong>: Uncaught TypeError: Unsupported operand types: null &amp; array in D:\xampp\htdocs\vendor\sabre\amf\lib\SabreAMF\AMF0\Deserializer.php:129 Stack trace: #0 D:\xampp\htdocs\vendor\sabre\amf\lib\SabreAMF\AMF0\Deserializer.php(67): SabreAMF_AMF0_Deserializer-&gt;readArray() #1 D:\xampp\htdocs\vendor\sabre\amf\lib\SabreAMF\Message.php(146): SabreAMF_AMF0_Deserializer-&gt;readAMFData(10, true) #2 D:\xampp\htdocs\vendor\sabre\amf\lib\SabreAMF\Server.php(79): SabreAMF_Message-&gt;deserialize(Object(SabreAMF_InputStream)) #3 D:\xampp\htdocs\Gateway.php(23): SabreAMF_Server-&gt;__construct() #4 {main} thrown in <strong>D:\xampp\htdocs\vendor\sabre\amf\lib\SabreAMF\AMF0\Deserializer.php</strong> on line <strong>129</strong></p>

Here is what the client sends:

![image](https://user-images.githubusercontent.com/50364607/187931424-802a9662-01ac-4a58-9cb3-d2628491e5e6.png)

Thank you in advance for your response, and I'm sorry to bother you if this is an old unmaintained project.

**Comment by evert** [comment]
Hi! It's been more than a decade since I worked on this. I no longer have the context to help. Whoever is interested in using this is probably on their own, but ill accept pull requests (mostly blindly)

**Comment by cy-polo** [comment]
Hello,

thank you for your answer, even if I'm annoyed that I can't solve this problem.
I understand that diving back into a project that can be used is no longer interesting.

Have a nice day!

**Comment by bastetcheat** [comment]
> 

hey , could you find solution to read amf data of family farm ?

**Comment by evert** [comment]
@bastetcheat this library has nothing to do with farming.

**Comment by ROBERT-MCDOWELL** [comment]
@evert 
family farm is a Flash game....

**Comment by evert** [comment]
ok, well that's still off-topic for this issue. Try to find a different venue for this question

**Comment by celeryness** [comment]
In case anyone else is looking at this issue, there are two solutions: use an older version of PHP (pre 8), or in AMFDeserializer.php on line 241 try changing the line that reads:

$this->storedObjects[] & = $data;

to

$this->storedObjects[] = &$data;
